---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Digital.ai - Official/Workflows/Secret Management
spec:
- template: Delete Secret in Azure KeyVault
  description: Easily delete secret entries from Azure KeyVault.
  scheduledStartDate: 2023-09-12T03:30:00Z
  phases:
  - phase: Delete Secret
    tasks:
    - name: Create|Select Azure KeyVault Connection
      type: xlrelease.UserInputTask
      description: Select or create a new Azure KeyVault connection.
      variables:
      - azure_key_vault
    - name: Specify Secret Details
      type: xlrelease.UserInputTask
      description: Enter the secret name to be deleted.
      variables:
      - vault_name
      - secret_name
    - name: Delete Secret
      type: azureKeyvault.DeleteSecret
      vaultName: "${vault_name}"
      secretName: "${secret_name}"
      description: Deletes the specified secret from the specified Azure KeyVault.
      variableMapping:
        pythonScript.keyvaultServer: "${azure_key_vault}"
    color: '#3d6c9e'
  kind: WORKFLOW
  categories:
  - Cloud & Container
  logo:
    type: xlrelease.TemplateLogo
    contentType: image/svg+xml
    file: !file "template-logo/xlr-azure-plugin.svg"
  variables:
  - type: xlrelease.StringVariable
    key: secret_name
    showOnReleaseStart: false
    label: Secret Name
    description: Name of the secret
  - type: xlrelease.PasswordStringVariable
    key: secret_value
    showOnReleaseStart: false
    label: Secret Value
    description: Value of the secret as plain text
  - type: xlrelease.ReferenceVariable
    key: azure_key_vault
    showOnReleaseStart: false
    label: Azure KeyVault Server
    description: Connection to Azure KeyVault
    referencedType: azure.KeyvaultServer
  - type: xlrelease.StringVariable
    key: vault_name
    showOnReleaseStart: false
    label: Vault Name
    description: Azure KeyVault Name
  author: Digital.ai
  defaultTargetFolder: Digital.ai - Official/Workflow Executions
