# Exported from:        http://Mayur-Patel:5516/
# Release version:      24.1.0
# Date created:         Mon Apr 15 12:13:27 IST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Permissions.yaml
  - Workflow_Create Secret in AWS SecretsManager.yaml
  - Workflow_Create Secret in Azure KeyVault.yaml
  - Workflow_Delete Secret in AWS SecretsManager.yaml
  - Workflow_Delete Secret in Azure KeyVault.yaml
  - Workflow_Update Secret in AWS SecretsManager.yaml
  - Workflow_Update Secret in Azure KeyVault.yaml
