# Exported from:        http://Mayur-Patel:5516/
# Release version:      24.1.0
# Date created:         Mon Apr 15 12:13:28 IST 2024

---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  path: Workflows/DORA
  home: Digital.ai - Official/Workflows/DORA
spec:
- directory: "."
  teams:
  - name: Release Admin
    permissions:
    - release#edit_failure_handler
    - release#edit_precondition
    - release#lock_task
  - name: Folder Owner
  - name: Template Owner
    permissions:
    - template#edit_failure_handler
    - template#edit_precondition
    - template#lock_task
  - name: Viewer
    roles:
    - Authenticated Users
    permissions:
    - folder#view
    - template#view
