---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Digital.ai - Official/Workflows/ArgoCD
spec:
- template: Delete Application in ArgoCD
  kind: WORKFLOW
  scheduledStartDate: 2023-04-27T18:30:00+05:30
  dueDate: 2023-04-27T19:30:00+05:30
  phases:
  - phase: Delete Application in ArgoCD
    tasks:
    - name: Application Details
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      variables:
      - projectDetails
      - argoCDApiServer
      - Application_name
    - name: Delete Application in ArgoCD
      type: argocd.RemoveApplication
      variableMapping:
        argoServer: "${argoCDApiServer}"
      capabilities:
      - remote
      applicationName: "${Application_name}"
    - name: Delete Application in Release
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
    color: '#3d6c9e'
  categories:
  - Application onboarding
  variables:
  - type: xlrelease.StringVariable
    key: Application_name
    showOnReleaseStart: false
    label: Application Name
    description: Application name to delete from ArgoCD
  - type: xlrelease.StringVariable
    key: projectDetails
    showOnReleaseStart: false
    label: Project Details
    description: Name of the project in ArgoCD where the Application is mapped to
    value: default
  - type: xlrelease.ReferenceVariable
    key: argoCDApiServer
    showOnReleaseStart: false
    label: ArgoCD API server
    description: ArgoCD Api Server connection details
    referencedType: argocd.APIServer
  scriptUsername: admin
  author: Digital.ai
  logo:
    type: xlrelease.TemplateLogo
    contentType: image/png
    file: !file "template-logo/argo-icon.png"
