# Exported from:        http://ip-172-31-12-123.ap-south-1.compute.internal:5516/
# Release version:      23.3.0-beta.5
# Date created:         Thu Aug 31 08:05:23 UTC 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Changes to argoCd workflows
spec:
- template: Delete Application in ArgoCD
  scheduledStartDate: 2023-04-27T13:00:00Z
  dueDate: 2023-04-27T14:00:00Z
  phases:
  - phase: Delete Application in ArgoCD
    tasks:
    - name: Application Details
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      owner: "${release.owner}"
      variables:
      - projectDetails
      - argoCDApiServer
      - Application_name
    - name: Delete Application in ArgoCD
      type: argocd.RemoveApplication
      owner: "${release.owner}"
      variableMapping:
        argoServer: "${argoCDApiServer}"
      capabilities:
      - remote
      applicationName: "${Application_name}"
    - name: Delete Application in Release
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      owner: "${release.owner}"
    color: '#3d6c9e'
  kind: WORKFLOW
  categories:
  - Application onboarding
  variables:
  - type: xlrelease.StringVariable
    key: Application_name
    showOnReleaseStart: false
    label: Application Name
    description: Application name to delete from ArgoCD
  - type: xlrelease.StringVariable
    key: projectDetails
    showOnReleaseStart: false
    label: Project Details
    description: Name of the project in ArgoCD where the Application is mapped to
    value: default
  - type: xlrelease.ReferenceVariable
    key: argoCDApiServer
    showOnReleaseStart: false
    label: ArgoCD API server
    description: ArgoCD Api Server connection details
    referencedType: argocd.APIServer
  scriptUsername: admin
  riskProfile: Default risk profile
  author: Digital.ai
  logo:
    type: xlrelease.TemplateLogo
    contentType: image/png
    file: !file "template-logo/01d81f95a92b5ebbae77081f9988c520aa79d73e/argo-icon.png"
