---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Permissions.yaml
  - Workflow_Install additional Digital.ai Release runner in Kubernetes.yaml
  - Workflow_Install Digital.ai Release runner in Kubernetes.yaml
  - Workflow_Install Digital.ai Release runner with Digital.ai Cloud Connector.yaml
