# Exported from:        http://ip-172-31-12-123.ap-south-1.compute.internal:5516/
# Release version:      23.3.0-beta.5
# Date created:         Thu Aug 31 07:46:46 UTC 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Workflow_AWS Lambda application setup with Digital.ai Deploy.yaml
  - Workflow_Azure Application setup with Digital.ai Deploy to create Azure resource
    groups.yaml
  - Workflow_GCP Application setup with Digital.ai Deploy for virtual machine instance.yaml
  - Workflow_Tomcat DataSource Setup on SSH Host with Digital.ai Deploy.yaml
  - Workflow_Websphere JaasAlias setup with Digital.ai Deploy.yaml
