---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Digital.ai - Official/Workflows/Digital.ai Deploy
spec:
- template: GCP Application setup with Digital.ai Deploy for virtual machine instance
  description: "Seamless create an application in Digital.ai Deploy that can set up\
    \ virtual machine instances in GCP, including its respective environment and infrastructure\
    \ configuration."
  scheduledStartDate: 2023-03-31T09:00:00+05:30
  dueDate: 2023-03-31T10:00:00+05:30
  kind: WORKFLOW
  phases:
  - phase: Setup Env and Infra
    tasks:
    - name: Specify Deploy Server Details
      type: xlrelease.UserInputTask
      description: Select the Deploy Server Connection onto which the Google Cloud
        Platform application has to be created. You can create a new connection if
        you have not created one.
      owner: admin
      variables:
      - deploy-server
    - name: Specify Environment Name
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      owner: admin
      variables:
      - environment_identifier
    - name: Create Environment
      type: deploy.CreateCI
      owner: admin
      variableMapping:
        server: "${deploy-server}"
      capabilities:
      - remote
      ciID: "Environments/${environment_identifier}"
      ciType: udm.Environment
      jsonDescriptor: "{}"
    - name: Specify Google Account Parameters
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      owner: admin
      variables:
      - google_account_cloud_name
      - gcp_project_id
      - gcp_client_email
      - private_key
    - name: Create Google Account Cloud Infra
      type: deploy.CreateCI
      owner: admin
      variableMapping:
        server: "${deploy-server}"
      capabilities:
      - remote
      ciID: "Infrastructure/${google_account_cloud_name}"
      ciType: google.AccountCloud
      jsonDescriptor: |-
        {
            "projectId": "${gcp_project_id}",
            "clientEmail": "${gcp_client_email}",
            "privateKey": "${private_key}"
        }
      addToEnvironment: true
      envID: "Environments/${environment_identifier}"
    - name: Check Connection of Google account
      type: deploy.ControlTask
      owner: admin
      variableMapping:
        server: "${deploy-server}"
      capabilities:
      - remote
      ciId: "Infrastructure/${google_account_cloud_name}"
      taskName: checkConnection
      numberOfContinueRetrials: 0
      pollingInterval: 10
      numberOfPollingTrials: 0
      displayStepLogs: true
      connectionRetries: 10
  - phase: Setup Application
    tasks:
    - name: Specify Application Name
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      owner: admin
      variables:
      - application_identifier
    - name: Create Application
      type: deploy.CreateCI
      owner: admin
      variableMapping:
        server: "${deploy-server}"
      capabilities:
      - remote
      ciID: "Applications/${application_identifier}"
      ciType: udm.Application
      jsonDescriptor: "{}"
    - name: Specify Package Name
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      owner: admin
      variables:
      - application_version
    - name: Create Deployment Package
      type: deploy.CreateCI
      owner: admin
      variableMapping:
        server: "${deploy-server}"
      capabilities:
      - remote
      ciID: "Applications/${application_identifier}/${application_version}"
      ciType: udm.DeploymentPackage
    - name: Specify Intance Spec Parameters
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      owner: admin
      variables:
      - zone
      - machine
      - image_project
      - image
      - wait_time_for_create
      - wait_time_for_destroy
    - name: Create Google Instance spec
      type: deploy.CreateCI
      owner: admin
      variableMapping:
        server: "${deploy-server}"
      capabilities:
      - remote
      ciID: "Applications/${application_identifier}/${application_version}/${instance_spec_name}"
      ciType: googlecloud.compute.InstanceSpec
      jsonDescriptor: |-
        {
            "zone": "${zone}",
            "machine": "${machine}",
            "imageProject": "${image_project}",
            "image": "${image}",
            "waitOnCreate": "${wait_time_for_create}",
            "waitOnDestroy": "${wait_time_for_destroy}"
        }
    - name: Add Managed Application
      type: xlrelease.ScriptTask
      owner: admin
      script: |-
        from com.xebialabs.xlrelease.api.v1.views import ManagedApplicationView
        from com.xebialabs.xlrelease.api.v1.views import ConnectionServerView
        from java.util import Date
        from java.text import SimpleDateFormat
        import datetime

        parsedDate = datetime.datetime.now()

        requestBody = ManagedApplicationView()
        requestBody.applicationName = "${application_identifier}"
        requestBody.managedBy = "Digital.ai Deploy"
        requestBody.dateCreated = parsedDate
        requestBody.environmentTag = "${environment_identifier}"
        requestBody.applicationReference = "${application_identifier}"

        connectionServer = ConnectionServerView('${deploy-server}', '', '', '')
        requestBody.connectionServer = connectionServer

        res = managedApplicationApi.addManagedApplication(requestBody)
    color: '#3d6c9e'
  tags:
  - app-pipeline-templates
  variables:
  - type: xlrelease.StringVariable
    key: environment_identifier
    value: gcp_env
  - type: xlrelease.StringVariable
    key: google_account_cloud_name
    value: google_cloud
  - type: xlrelease.StringVariable
    key: gcp_project_id
    value: gcp_project_id
  - type: xlrelease.StringVariable
    key: private_key
    value: gcp_private_key
  - type: xlrelease.StringVariable
    key: application_identifier
    value: gcp_app
  - type: xlrelease.StringVariable
    key: application_version
    value: app_version
  - type: xlrelease.StringVariable
    key: instance_spec_name
    value: gcp_instance_spec_name
  - type: xlrelease.StringVariable
    key: machine
    value: machine
  - type: xlrelease.StringVariable
    key: image_project
    value: image_project
  - type: xlrelease.StringVariable
    key: zone
    value: zone
  - type: xlrelease.StringVariable
    key: image
    value: image
  - type: xlrelease.StringVariable
    key: wait_time_for_create
    value: wait_for_create
  - type: xlrelease.StringVariable
    key: wait_time_for_destroy
    value: wait_time_for_destroy
  - type: xlrelease.StringVariable
    key: gcp_client_email
    value: gcp_client_email
  - type: xlrelease.ReferenceVariable
    key: deploy-server
    showOnReleaseStart: false
    label: Deploy Server
    referencedType: digitalai.DeployServer
  - type: xlrelease.StringVariable
    key: application-name
  - type: xlrelease.StringVariable
    key: environment-name
  riskProfile: Default risk profile
  author: Digital.ai
  categories:
  - Cloud & Container
  - Application Life Cycle Management
  logo:
    type: xlrelease.TemplateLogo
    contentType: image/png
    file: !file "template-logo/xlr-xld-plugin.png"