# Exported from:        http://admins-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Tue Mar 04 11:06:04 CET 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_Configure Release.yaml
  - Template_Guided Tour for Release Managers.yaml
  - Template_Sample Release Template.yaml
  - Template_Welcome to Release!.yaml
