---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Digital.ai - Official/Workflows/FluxCD
spec:
- template: Workflow_FluxCD delete application
  description: Deletes FluxCD deployment and ints manifests
  scheduledStartDate: 2025-04-10T09:00:00+02:00
  phases:
  - phase: Workflow tasks
    tasks:
    - name: Get configuration details
      type: xlrelease.ScriptTask
      script: |-
        from com.xebialabs.xlrelease.domain.environments import LiveDeployment

        liveDeployment = deploymentServerApi.getLiveDeployment("")
        applicationName = liveDeployment.getApplication().getTitle().split(":")[0]
        statusWebhookEventSource = configurationApi.getConfiguration(liveDeployment.eventSourceId)

        releaseVariables['statusWebhookEventSourceId'] = statusWebhookEventSource.id
        releaseVariables['applicationName'] = applicationName
        releaseVariables['fluxCDApiServer'] = statusWebhookEventSource["sourceServer"].id
    - name: Application details
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      variables:
      - sourceName
      - sourceNamespace
      - deploymentName
      - deploymentNamespace
      - sourceManifestName
      - deploymentManifestName
    - name: Delete source manifest
      type: fluxcd.DeleteSource
      variableMapping:
        server: "${fluxCDApiServer}"
        gitRepository: "${gitRepository}"
      capabilities:
      - remote
      manifestFilename: "${sourceManifestName}"
      resourceName: "${sourceName}"
      namespace: "${sourceNamespace}"
      kind: GitRepository
    - name: Delete deployment manifest
      type: fluxcd.DeleteApplication
      variableMapping:
        server: "${fluxCDApiServer}"
        gitRepository: "${gitRepository}"
      capabilities:
      - remote
      manifestFilename: "${deploymentManifestName}"
      resourceName: "${deploymentName}"
      namespace: "${deploymentNamespace}"
      kind: Kustomization
    - name: Delete configuration
      type: xlrelease.ScriptTask
      script: |-
        statusWebhookEventSource = configurationApi.getConfiguration("${statusWebhookEventSourceId}")
        liveDeploymentConfigs = statusWebhookEventSource.getProperty("liveDeploymentConfigs")
        applicationToDelete = ""

        configToDelete = None
        for config in liveDeploymentConfigs:
            if config.getProperty("application") == applicationToDelete:
                configToDelete = config
                break

        if configToDelete:
            liveDeploymentConfigs.remove(configToDelete)
            statusWebhookEventSource.setProperty("liveDeploymentConfigs", liveDeploymentConfigs)
            configurationApi.updateConfiguration("${statusWebhookEventSourceId}", statusWebhookEventSource)
            configurationApi.deleteConfiguration(configToDelete.id)
  kind: WORKFLOW
  tags:
  - Remote FluxCD
  - application
  - delete
  - internal
  variables:
  - type: xlrelease.StringVariable
    key: sourceName
    showOnReleaseStart: false
  - type: xlrelease.StringVariable
    key: deploymentName
    showOnReleaseStart: false
  - type: xlrelease.StringVariable
    key: sourceNamespace
    showOnReleaseStart: false
  - type: xlrelease.StringVariable
    key: deploymentNamespace
    showOnReleaseStart: false
  - type: xlrelease.StringVariable
    key: sourceManifestName
    requiresValue: false
    showOnReleaseStart: false
  - type: xlrelease.StringVariable
    key: deploymentManifestName
    requiresValue: false
    showOnReleaseStart: false
  - type: xlrelease.StringVariable
    key: statusWebhookEventSourceId
    requiresValue: false
    showOnReleaseStart: false
  - type: xlrelease.StringVariable
    key: liveDeploymentId
    requiresValue: false
    showOnReleaseStart: false
  - type: xlrelease.ReferenceVariable
    key: fluxCDApiServer
    requiresValue: false
    showOnReleaseStart: false
    referencedType: fluxcd.APIServer
  - type: xlrelease.ReferenceVariable
    key: gitRepository
    requiresValue: false
    showOnReleaseStart: false
    referencedType: fluxcd.GitConfig
  - type: xlrelease.StringVariable
    key: sourceKind
    requiresValue: false
    showOnReleaseStart: false
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - GitRepository
      - HelmRepository
      - HelmChart
      - OCIRepository
  - type: xlrelease.StringVariable
    key: deploymentKind
    requiresValue: false
    showOnReleaseStart: false
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - Kustomization
      - HelmRelease
  - type: xlrelease.StringVariable
    key: applicationName
    requiresValue: false
    showOnReleaseStart: false
  disableNotifications: true
  author: Digital.ai
  logo:
    type: xlrelease.TemplateLogo
    contentType: image/png
    file: !file "template-logo/b949355de09e9b9e833c07ea8bbe02d466256a6a/fluxcd.svg"