# This workflow will execute xl-cli apply on newly created or updated yaml files to verify it is not using non-official/non default plugins and yaml syntax

name: Verify Digital.ai Official workflow and templates
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  run_xl_apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release-content Repository
        uses: actions/checkout@v3

      - name: Get Target Branch Name
        run: echo "TARGET_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV

      - name: Print Target Branch Name
        run: echo "Target branch is $TARGET_BRANCH"

      - name: Get docker and xl-cli version name from version.json
        run: |
          VAR_FILE=".github/config/versions.json"
          if [ -f "$VAR_FILE" ]; then
              echo "json file is $VAR_FILE"
              echo "target branch is $TARGET_BRANCH"
              xlr_docker_version=$(jq -r --arg branch "$TARGET_BRANCH" '.[$branch]["releaseVersion"]' "$VAR_FILE")
              xlcli_version=$(jq -r --arg branch "$TARGET_BRANCH" '.[$branch]["xlCliVersion"]' "$VAR_FILE")
              echo "XLR docker version to be used is : $xlr_docker_version"
              echo "xl-cli version to be used is :  $xlcli_version"
              echo "xlr_docker_version=$xlr_docker_version" >> $GITHUB_ENV
              echo "xlcli_version=$xlcli_version" >> $GITHUB_ENV
          else
            echo "File $VAR_FILE does not exist"
          fi
          echo "Debug: xlr_docker_version=$xlr_docker_version"
          echo "Debug: xlcli_version=$xlcli_version"

      - name: Print version got from json
        run: echo "XLR docker version is $xlr_docker_version and xl-cli version is $xlcli_version from versions.json"

      - name: Pull Release Docker image
        run: docker pull xebialabsunsupported/xl-release:$xlr_docker_version

      - name: Run Docker container
        run: |
          docker run -p 5516:5516 -d --name xlr$xlr_docker_version -e "ACCEPT_EULA=Y" -e "ADMIN_PASSWORD=admin" xebialabsunsupported/xl-release:$xlr_docker_version
          sleep 100

      - name: Download and Install xl-cli
        run: |
          wget https://dist.xebialabs.com/public/xl-cli/$xlcli_version/linux-amd64//xl -O xl1
          chmod 755 xl1
          ./xl1 version

      - name: Get changed YAML files
        id: changed-files
        uses: actions/github-script@v6
        with:
          script: |
            const changedFiles = await github.paginate(
              github.rest.pulls.listFiles,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
              }
            );
            const yamlFiles = changedFiles
              .filter(file => file.filename.endsWith('.yaml') || file.filename.endsWith('.yml'))
              .map(file => file.filename)
              .join('\n');
            return yamlFiles;

      - name: Apply YAML files to check if xl-apply works
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.result }}
        run: |
          IFS=$'\n'
          for file in $(echo -e "$ALL_CHANGED_FILES"); do
            file=$(echo "$file" | sed 's/^"//;s/"$//')
            echo "$file was changed"
            ./xl1 apply -f "$file"
          done
