# This workflow will execute xl cli apply on newly created or updated yaml files. 

name: xl-apply with xlr container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  run_xl_apply:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout release-content Repository
        uses: actions/checkout@v3
        
      - name: Download and Install xl-cli
        run: |
         wget https://nexus.xebialabs.com/nexus/content/repositories/releases/com/xebialabs/xlclient/xl-client/23.3.5/xl-client-23.3.5-linux-amd64.bin --user=${{ secrets.NEXUS_USERNAME }} --password=${{ secrets.NEXUS_PASSWORD }} -O xl1
         chmod 755 xl1
         ./xl1 --version 
          
